apiVersion: apps/v1
kind: Deployment
metadata:
  name: hugo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hugo
  template:
    metadata:
      labels:
        app: hugo
    spec:
      containers:
      - name: hugo
        image: yourusername/hugoblog:latest
        ports:
        - containerPort: 80
